{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "from pathlib import Path\n",
    "import numpy as np\n",
    "import geopy\n",
    "from geopy.geocoders import Nominatim\n",
    "\n",
    "total_result = 0\n",
    "counter = 0\n",
    "DATA_DIR = Path('data')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    " def place_to_gps(place):\n",
    "        global counter, total_result\n",
    "        counter+=1\n",
    "        if counter%10==True:\n",
    "            print(f\"{round(counter/total_result, 3)}%\")\n",
    "        try:\n",
    "            location = geolocator.geocode(place)\n",
    "            # If coordinates are found for location\n",
    "            if location:\n",
    "                country = location.address.rsplit(',', 1)[1]\n",
    "                return pd.Series([location.latitude, location.longitude, location.address, location.altitude, location.point, country])\n",
    "\n",
    "        except geopy.exc.GeopyError as err:\n",
    "            print(\"geopy_exc_geopyerror\")\n",
    "            print(err)\n",
    "            print(place)\n",
    "            return pd.Series([np.nan, np.nan, np.nan, np.nan, np.nan, np.nan])\n",
    "        except geopy.exc.ConfigurationError as err:\n",
    "            print(\"geopy_exc_ConfigurationError\")\n",
    "            print(err)\n",
    "            print(place)\n",
    "            return pd.Series([np.nan, np.nan, np.nan, np.nan, np.nan, np.nan])\n",
    "        except geopy.exc.GeocoderServiceError as err:\n",
    "            print(\"geopy_exc_GeocoderServiceError\")\n",
    "            print(err)\n",
    "            print(place)\n",
    "            return pd.Series([np.nan, np.nan, np.nan, np.nan, np.nan, np.nan])\n",
    "        except geopy.exc.GeocoderQueryError as err:\n",
    "            print(\"geopy_exc_GeocoderQueryError\")\n",
    "            print(err)\n",
    "            print(place)\n",
    "            return pd.Series([np.nan, np.nan, np.nan, np.nan, np.nan, np.nan])\n",
    "        except geopy.exc.GeocoderQuotaExceeded as err:\n",
    "            print(\"geopy_exc_GeocoderQuotaExceeded\")\n",
    "            print(err)\n",
    "            print(place)\n",
    "            return pd.Series([np.nan, np.nan, np.nan, np.nan, np.nan, np.nan])\n",
    "        except geopy.exc.GeocoderAuthenticationFailure as err:\n",
    "            print(\"geopy_exc_GeocoderAuthenticationFailure\")\n",
    "            print(err)\n",
    "            print(place)\n",
    "            return pd.Series([np.nan, np.nan, np.nan, np.nan, np.nan, np.nan])\n",
    "        except geopy.exc.GeocoderInsufficientPrivileges as err:\n",
    "            print(\"geopy_exc_GeocoderInsufficientPrivileges\")\n",
    "            print(err)\n",
    "            print(place)\n",
    "            return pd.Series([np.nan, np.nan, np.nan, np.nan, np.nan, np.nan])\n",
    "        except geopy.exc.GeocoderTimedOut as err:\n",
    "            print(\"geopy_exc_GeocoderTimedOut\")\n",
    "            print(err)\n",
    "            print(place)\n",
    "            return pd.Series([np.nan, np.nan, np.nan, np.nan, np.nan, np.nan])\n",
    "        except geopy.exc.GeocoderUnavailable as err:\n",
    "            print(\"geopy_exc_GeocoderUnavailable\")\n",
    "            print(err)\n",
    "            print(place)\n",
    "            return pd.Series([np.nan, np.nan, np.nan, np.nan, np.nan, np.nan])\n",
    "        except geopy.exc.GeocoderParseError as err:\n",
    "            print(\"geopy_exc_GeocoderParseError\")\n",
    "            print(err)\n",
    "            print(place)\n",
    "            return pd.Series([np.nan, np.nan, np.nan, np.nan, np.nan, np.nan])\n",
    "        except geopy.exc.GeocoderNotFound as err:\n",
    "            print(\"geopy_exc_GeocoderNotFound\")\n",
    "            print(err)\n",
    "            print(place)\n",
    "            return pd.Series([np.nan, np.nan, np.nan, np.nan, np.nan, np.nan])\n",
    "        except:\n",
    "            print(\"unknown error\")\n",
    "            return pd.Series([np.nan, np.nan, np.nan, np.nan, np.nan, np.nan])\n",
    "\n",
    "        return pd.Series([np.nan, np.nan, np.nan, np.nan, np.nan, np.nan])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "dfs = {}\n",
    "for fname in DATA_DIR.glob('*.pkl'):\n",
    "    print(f'Reading data from {fname}')\n",
    "    dfs[fname.name.split('_')[0]] = pd.read_pickle(fname)\n",
    "\n",
    "    \n",
    "    df = pd.concat(dfs.values(), axis=0)\n",
    "    result = df['user.location'].mask(df['user.geo_enabled'], other=np.nan)\n",
    "    geolocator = Nominatim(user_agent=\"tapp\")\n",
    "    \n",
    "    counter = 0\n",
    "    total_result = len(result)\n",
    "    df[['geo_latitude', 'geo_longitude', 'geo_address', 'geo_altitude', 'geo_point', 'geo_country']] = result.apply(place_to_gps)\n",
    "\n",
    "    print(df)\n",
    "\n",
    "    df.to_pickle(f'geo_{fname}.pkl')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
